name: Generate GitArtWork

on:
workflow_dispatch:

jobs:
build:
runs-on: ubuntu-latest

```
steps:
  - uses: actions/checkout@v4

  - uses: jasineri/gitartwork@v1
    with:
      user_name: nguyentuanquang2210
      text: QUANG

  - name: Commit SVG
    run: |
      git config user.name "github-actions[bot]"
      git config user.email "github-actions[bot]@users.noreply.github.com"

      git add .
      git commit -m "Update gitartwork.svg" || echo "No changes"

      git push
```
